var appConstants = {
    SAMPLE_ITEM: "SAMPLE_ITEM",
    SAVE_SOCKET_ID: 'SAVE_SOCKET_ID',
    COMPONENT_READY: 'COMPONENT_READY',
    BINGO_ROOMS: 'BINGO_ROOMS',
    JOIN_ROOM: 'JOIN_ROOM',
    LEAVE_ROOM: 'LEAVE_ROOM'

};

module.exports = appConstants;